### PR TITLE
exitOnClose setting, tested on debian sid

### PR DESCRIPTION
**Pull request by cnheider**

### CODE REVIEW

**Comment by vincelwt** [comment]
Thanks!
However it lacks some clarity, is it to prevent the app from quitting when we try to close the window ? Because except on MacOS the app already quits when we close the window 
(I can't currently try it)

**Comment by cnHeider** [comment]
Yes that was the intended behavior, the default of the PR is to prevent the user from quitting the app by alt-f4 or clicking the x on the window, exitOnClose set to false. The user can still quit the app by right click -> Quit on the tray icon.

**Comment by cnHeider** [comment]
Something else to look into as a setting is to show/focus an already running instance of the app, if any, instead of creating a new.

**Comment by vincelwt** [comment]
The problem is if the user didn't enabled the Tray, how can he quit the app ? Maybe enable the checkbox only if the tray is enabled ? I'll take a look at that

**Comment by mike168m** [comment]
Why not make the tray icon show by default?

**Comment by vincelwt** [comment]
Closing since not opensource anymore

**Pull request closed without merging**
