### PR TITLE
Add GooglePM IFL and Custom stations

### PR DESCRIPTION
**Pull request by w0xel**
googlepm_discover
bildschirmfoto von 2016-10-06 16 54 27

"Radio" is always only the last custom station created.

### CODE REVIEW

**Comment by vincelwt** [comment]
Nice :)

For me, pm.createStation returns a 400:
`googlepm.js:168 Error: error getting station tracks: Error: 400 error from server(…)`

It may be due to my country ?
https://support.google.com/googleplay/answer/6230658?hl=en

Also, when you want to return with an error in googlepm.fetchData, you need to do
`if (err) return reject([err]);`
instead of
`if (err) return console.log(err);`

Because this function is actually a Promise.
`err `must be in an array, in case the error is a login problem we add `[err, true] ` so the app open the settings with an error.

**Comment by vincelwt** [comment]
Actually after some try if we put the resolve after the createStation, then even if there is an error it will load correctly, I'll merge and fix it

**Comment by w0xel** [comment]
Mhh. I didn't think about that. I can reproduce the HTML 400 error when trying to use an uploaded song to create a station, i guess this has to to be checked. Songs from Google work fine. Also i guess this feature has to depend on a subscription. The best solution would probably be harmony just trying to get a station (for users in US/canada). Is there any way of checking if a song is uploaded or from google play?

**Comment by vincelwt** [comment]
Yes, it always fail when it falls on a uploaded track, I'm trying to fix it, maybe by paid tracks when they're added to thumbs up ?

**Comment by vincelwt** [comment]
@w0xel Ok I should've fixed it, by popping a notification when the track isn't compatible with stations, and by only creating IFL from all access tracks (I also passed the code to a JS beautifier)

**Pull request merged**
