### PR TITLE
Fix sorting thumbs up

### PR DESCRIPTION
**Pull request by w0xel**
Fix the sort algorithm for undefined timestamps.

### CODE REVIEW

**Comment by vincelwt** [comment]
Thanks!

Just, wouldn't it be better to` return -1;` if a or b are undefined ? So we can put every old liked tracks (if it's what they are) to the bottom.

**Comment by w0xel** [comment]
returning -1 when a is undefined would mean a is newer than b. We want "'undefined' is older than everything". That's why it's 1 for a == undefined and -1 for b == undefined

**Comment by vincelwt** [comment]
If we return 1, (so when **a** is undefined) then **a** would be considered newer than **b**.
Now if **a** is undefined but **b** is not, we want **b** > **a**, and we do so  by returning -1;

What we want is :

**Comment by vincelwt** [comment]
If we return 1, then we indicate than **a** is newer than **b**.
Now if **a** is undefined but **b** is not, we want **b** > (newer than) **a**, and we do so by returning -1. 


See [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Creating_displaying_and_sorting_an_array)

What we want is:

if a & b are undefined
     return 0 ( but this condition isn't needed as they will be down in every case)
if a is defined but b is undefined 
    return 1 (a > b)
if a is undefined but b is defined 
   return -1 (b > a)

which translated into code:

```
if (a && typeof b.RatingTimestamp == 'undefined')
   return 1;
else if (b && typeof a.RatingTimestamp == 'undefined')
 return -1;

```

Do you agree ?

**Comment by w0xel** [comment]
Quite. Doing the extra check (a.RatingTimestamp && ... ) is not needed, as thats why i added the 'typeof' statement. That gives 'undefined' if the variable is not declared does not exist, or has no value. It's already a safe check.

**Comment by vincelwt** [comment]
Oops yeah no need for the check (a.RatingTimestamp && ... ).

So I think you mixed -1 and 1 in the code, because if a is undefined, we want to return -1

**Comment by w0xel** [comment]
Ah, no. You have to think backwards, as sort() wants to sort an array low to high, but we want high to low. Thats why you already put (b.RatingTimestamp - a.RatingTimestamp). That gives a positive number if b is greater than a. But as we call sort(a, b) sort counts it as a > b (backwards as said). If we return -1, sort thinks a is the smaller object, and this is what we want.

**Comment by w0xel** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by vincelwt** [comment]
Oops yeah you were right! sorry, I missed the point

**Comment by vincelwt** [comment]
Fix #47

**Pull request merged**
