### PR TITLE
Arc theme almost integrate [WIP]

### PR DESCRIPTION
**Pull request by mandruis**
Working on it

### CODE REVIEW

**Comment by vincelwt** [comment]
Hi!
Thanks for the contribution :)
Some things to correct:
- Maybe in the future Ctrl+a will be used to select all tracks, so I don't think it should be used to toggle this one. Maybe add an option to select a dark style between normal dark and your arc ? So we only keep Ctrl+d 
- About the CSS transitions, I don't think they should be in a subtheme, they should be in the main CSS so they work with all themes. You could maybe put it on another Pull request ?

**Comment by mandruis** [comment]
Hi!
Thank you for the information i will try to make a new pull request with all the conditions you said.

**Comment by NickFlamel** [comment]
Why not just have a drop-down in the settings page for themes, one for dark mode and one for light mode? So if people want to make their own themes, they can add them easily

**Comment by vincelwt** [comment]
@NickFlamel Next release will now support external themes. 
Themes will be added to https://github.com/vincelwt/harmony-themes/

@mandruis I'll try adapting your theme to add it to the repo.

**Pull request closed without merging**
